import { useState } from 'react'

interface StaticVisualizationProps {
  imageUrl: string
  title: string
  altText: string
  onGenerate?: () => void
  isGenerating?: boolean
}

/**
 * Display static PNG visualizations generated by the real
 * visualization utilities (matplotlib-based)
 *
 * This ensures we show the EXACT same visualizations as
 * attention-viz-demo, not approximations
 */
export default function StaticVisualization({
  imageUrl,
  title,
  altText,
  onGenerate,
  isGenerating = false
}: StaticVisualizationProps) {
  const [imageError, setImageError] = useState(false)
  const [imageLoaded, setImageLoaded] = useState(false)

  const handleImageError = () => {
    setImageError(true)
  }

  const handleImageLoad = () => {
    setImageLoaded(true)
    setImageError(false)
  }

  return (
    <div className="flex flex-col h-full">
      <div className="mb-2 flex justify-between items-center">
        <h3 className="text-sm font-medium text-black">
          {title}
        </h3>
        {onGenerate && (
          <button
            onClick={onGenerate}
            disabled={isGenerating}
            className="text-xs btn-secondary disabled:opacity-50"
          >
            {isGenerating ? 'Generating...' : 'Regenerate'}
          </button>
        )}
      </div>

      <div className="flex-1 bg-white border border-gray-200 rounded-lg overflow-hidden relative">
        {!imageLoaded && !imageError && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-black"></div>
          </div>
        )}

        {imageError ? (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-500">
            <svg
              className="w-16 h-16 mb-2"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
              />
            </svg>
            <p className="text-sm">Visualization not available</p>
            <p className="text-xs mt-1">Generate using "Run Inference"</p>
            {onGenerate && (
              <button
                onClick={onGenerate}
                className="mt-4 text-xs btn-primary"
              >
                Generate Now
              </button>
            )}
          </div>
        ) : (
          <img
            src={imageUrl}
            alt={altText}
            onError={handleImageError}
            onLoad={handleImageLoad}
            className={`w-full h-full object-contain transition-opacity duration-300 ${
              imageLoaded ? 'opacity-100' : 'opacity-0'
            }`}
          />
        )}
      </div>

      <div className="mt-2 text-xs text-gray-600 text-center">
        Generated by matplotlib (real visualization utility)
      </div>
    </div>
  )
}
